apiVersion: v1
kind: ConfigMap
metadata:
  name: docker
  namespace: weavek8sops
data:
  daemon.json: |
    {
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "insecure-registries" : [
        "172.17.0.222:5000"
      ],
      "exec-opts": [
        "native.cgroupdriver=cgroupfs"
      ]
    }
